<a href="https://colab.research.google.com/github/pySin/PytorchTutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

Lists

In [2]:
list_1 = [[1, 2, 3, 4], [6, 7]]
print(f"My list: {list_1}")

My list: [[1, 2, 3, 4], [6, 7]]


Arrays

In [5]:
np_1 = np.random.rand(4, 4)
np_1

array([[0.20602169, 0.38007119, 0.15592516, 0.50211512],
       [0.93797667, 0.3488808 , 0.95875958, 0.14172859],
       [0.68993076, 0.81110526, 0.18850817, 0.37127732],
       [0.38927571, 0.43516792, 0.67533001, 0.4478796 ]])

Tensors

In [6]:
tensor_first = torch.rand(4, 4)
tensor_first

tensor([[0.7532, 0.6366, 0.8528, 0.9001],
        [0.4143, 0.9369, 0.5449, 0.6044],
        [0.1045, 0.9618, 0.8616, 0.4447],
        [0.7867, 0.9645, 0.1106, 0.8854]])

In [7]:
tensor_3d = torch.rand(3, 3, 4)
tensor_3d

tensor([[[0.4228, 0.9556, 0.6340, 0.2899],
         [0.6080, 0.4377, 0.7523, 0.8570],
         [0.2921, 0.3458, 0.2459, 0.0237]],

        [[0.4243, 0.1146, 0.5975, 0.3988],
         [0.1493, 0.9581, 0.6236, 0.5227],
         [0.2255, 0.2780, 0.0022, 0.1066]],

        [[0.5991, 0.8017, 0.6107, 0.2694],
         [0.3722, 0.7176, 0.9561, 0.5736],
         [0.9525, 0.5514, 0.2732, 0.3082]]])

In [9]:
tensor_3dz = torch.zeros(3, 3, 4)
tensor_3dz

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# Create a tensor from a numpy array
tensor_arr = torch.tensor(np_1)
tensor_arr

tensor([[0.2060, 0.3801, 0.1559, 0.5021],
        [0.9380, 0.3489, 0.9588, 0.1417],
        [0.6899, 0.8111, 0.1885, 0.3713],
        [0.3893, 0.4352, 0.6753, 0.4479]], dtype=torch.float64)